### ISSUE TITLE
Insonsistency between README.md and actual implementation

### ISSUE THREAD

**Issue by yuya-takeyama** [tcnksm/cli-init#8]
Current README.md says like this.

>- **main.go** - defines main function. It includes application name, version, usage, author name and so on.

But actual implementation generates APPNAME.go.
Which is correct?

IMHO, I prefer main.go.

**Comment by yuya-takeyama** [comment]
Oops.
I'll resolve this conflict and re-push.
![conflict](http://i.gyazo.com/570c61585038d9def1bfc5f369faeaea.png)

**Comment by tcnksm** [comment]
Sorry for late, new version of `cli-init` uses `main.go`.

Thanks
